version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64  # 确保跨平台兼容
    ports:
      - "5000:5000"
    volumes:
      - uploads_volume:/app/static/uploads  # 使用命名卷更好管理
      - ./model:/app/model
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1  # 3.12推荐设置
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  uploads_volume: